project:
  type: book
  output-dir: docs

book:
  title: "Learning Deep Learning"
  chapters:
    - index.qmd
    - neural-networks.qmd
    - learning.qmd
    - mnist.qmd
    - project-numerical-differentiation.qmd

format:
  html:
    theme: cosmo
