project:
  type: book
  output-dir: docs

book:
  title: "Learning Deep Learning"
  chapters:
    - index.qmd
    - neural-networks.qmd
    - learning.qmd
    - mnist.qmd
    - numerical-differentiation.qmd
    - numpy.qmd
    - backpropagation.qmd
    - tensors.qmd

format:
  html:
    theme: cosmo
